theme="github_dark_dimmed"

[keys.normal]
"C-s" = ":w"
"C-w" = ":buffer-close"
"C-x" = ["yank_to_clipboard", "delete_selection"]
"A-S-o" = "file_picker"
"C-c" = "yank_to_clipboard"
"C-v" = ["normal_mode", "paste_clipboard_before"]
"S-tab" = "unindent"
"tab" = "indent"
"C-left" = "move_prev_word_start"
"C-right" = ["move_next_word_end", "move_char_right"]
"C-S-left" = ["extend_prev_word_start"]
"C-S-right" = ["extend_next_word_end"]
"A-S-up" = "copy_selection_on_prev_line"
"A-S-down" = "copy_selection_on_next_line"
"d" = { "d" = "kill_to_line_end"}
"S-left" = ["move_char_right", "select_mode", "move_char_left"]  
"S-right" = ["move_char_left", "select_mode", "move_char_right"]
"S-up" = ["move_line_down", "select_mode", "move_line_up"]
"S-down" = ["move_line_up", "select_mode", "move_line_down"]
"$" = "goto_line_end"
"C-z" = "undo"
"C-y" = "redo"
"C-f" = "search"
"ret" = ["insert_mode", "open_below"]
"A-S-q" = { a = "code_action", r = "rename_symbol", e = "diagnostics_picker" }
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"F12" = "goto_definition"
"A-m" = "symbol_picker"
"C-backspace" = "delete_word_backward"
"C-del" = "delete_word_forward"
"C-a" = ["goto_file_start", "select_mode", "goto_file_end"]
"C-d" = ["extend_to_line_bounds", "yank", "paste_after"]


[keys.insert]
"C-s" = ":w"
"C-w" = ":buffer-close"
"C-x" = ["yank_to_clipboard", "delete_selection"]
"A-S-o" = "file_picker"
"C-c" = "yank_to_clipboard"
"C-v" = ["normal_mode", "paste_clipboard_before"]
"S-tab" = "unindent"
"C-left" = "move_prev_word_start"
"C-right" = ["move_next_word_end", "move_char_right"]
"C-S-left" = ["extend_prev_word_start"]
"C-S-right" = ["extend_next_word_end"]
"C-f" = "search"
"S-left" = ["move_char_right", "select_mode", "move_char_left"]  
"S-right" = ["move_char_left", "select_mode", "move_char_right"]
"S-up" = ["move_line_down", "select_mode", "move_line_up"]
"S-down" = ["move_line_up", "select_mode", "move_line_down"]
"C-z" = "undo"
"C-y" = "redo"
"A-S-q" = { a = "code_action", r = "rename_symbol", e = "diagnostics_picker" }
"A-down" = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-m" = "symbol_picker"
"C-backspace" = "delete_word_backward"
"C-del" = "delete_word_forward"
"C-a" = ["goto_file_start", "select_mode", "goto_file_end"]
"F12" = "goto_definition"


[keys.select]
"S-left" = "extend_char_left"
"S-right" = "extend_char_right"
"S-up" = "extend_line_up"
"S-down" = "extend_line_down"
"C-c" = "yank_to_clipboard"
"C-v" = ["insert_mode", "paste_clipboard_before"]
"C-f" = "search"
"C-x" = ["yank_to_clipboard", "delete_selection"]
"C-z" = "undo"
"C-y" = "redo"
"A-S-q" = { a = "code_action", r = "rename_symbol", e = "diagnostics_picker" }
"F12" = "goto_definition"
"A-m" = "symbol_picker"
"C-backspace" = "delete_word_backward"
"C-del" = "delete_word_forward"
"C-a" = ["goto_file_start", "select_mode", "goto_file_end"]
